import os
import time
import smtplib
import requests
from datetime import datetime, timezone
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


# === Config ===

DUNE_API_KEY   = os.environ["DUNE_API_KEY"]
QUERY_ID       = os.environ["DUNE_QUERY_ID"]       # S5 query ID (integer string)
THRESHOLD      = float(os.environ.get("THRESHOLD", "7.0"))   # default 7%

SMTP_HOST      = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT      = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER      = os.environ["SMTP_USER"]           # sender Gmail
SMTP_PASSWORD  = os.environ["SMTP_PASSWORD"]       # Gmail App Password
ALERT_TO       = os.environ["ALERT_TO"]            # recipient email

DUNE_BASE      = "https://api.dune.com/api/v1"
HEADERS        = {"X-Dune-Api-Key": DUNE_API_KEY}



# === Dune API ===

def execute_query(query_id: str) -> str:
    """Trigger query execution, return execution_id."""
    url  = f"{DUNE_BASE}/query/{query_id}/execute"
    resp = requests.post(url, headers=HEADERS, json={"performance": "medium"})
    resp.raise_for_status()
    execution_id = resp.json()["execution_id"]
    print(f"[INFO] Execution started: {execution_id}")
    return execution_id


def wait_for_results(execution_id: str, timeout: int = 300) -> list[dict]:
    """Poll until execution completes, return rows."""
    url     = f"{DUNE_BASE}/execution/{execution_id}/results"
    elapsed = 0
    while elapsed < timeout:
        resp = requests.get(url, headers=HEADERS)
        resp.raise_for_status()
        data   = resp.json()
        state  = data.get("state", "")
        print(f"[INFO] State: {state} ({elapsed}s)")

        if state == "QUERY_STATE_COMPLETED":
            return data["result"]["rows"]
        elif state in ("QUERY_STATE_FAILED", "QUERY_STATE_CANCELLED"):
            raise RuntimeError(f"Query failed with state: {state}")

        time.sleep(10)
        elapsed += 10

    raise TimeoutError(f"Query did not complete within {timeout}s")


def get_latest_wash_pct(rows: list[dict]) -> tuple[str, float]:
    """
    Extract the most recent day's wash trading %.
    Expects columns: block_date, wash_trading_pct  (adjust if your column names differ)
    """
    if not rows:
        raise ValueError("No rows returned from Dune query")

    # Sort by date descending and take the first row
    sorted_rows = sorted(rows, key=lambda r: r.get("block_date", ""), reverse=True)
    latest      = sorted_rows[0]

    # ── Adjust these keys to match your actual Dune column names ──
    
    date_val = latest.get("day") or "unknown"
    pct_val  = float(latest.get("wash_pct") or 0)
    
    return str(date_val), pct_val


# === Email ===

def build_email(date: str, pct: float, threshold: float) -> MIMEMultipart:
    subject = f"🚨 Wash Trading Alert – {pct:.2f}% detected on {date}"

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#222;">
      <h2 style="color:#d32f2f;">⚠️ Wash Trading Threshold Exceeded</h2>
      <table style="border-collapse:collapse;width:380px;">
        <tr style="background:#fce4e4;">
          <td style="padding:10px;border:1px solid #e0e0e0;"><b>Date</b></td>
          <td style="padding:10px;border:1px solid #e0e0e0;">{date}</td>
        </tr>
        <tr>
          <td style="padding:10px;border:1px solid #e0e0e0;"><b>Wash Trading %</b></td>
          <td style="padding:10px;border:1px solid #e0e0e0;color:#d32f2f;font-size:1.3em;">
            <b>{pct:.2f}%</b>
          </td>
        </tr>
        <tr style="background:#fce4e4;">
          <td style="padding:10px;border:1px solid #e0e0e0;"><b>Threshold</b></td>
          <td style="padding:10px;border:1px solid #e0e0e0;">{threshold:.1f}%</td>
        </tr>
        <tr>
          <td style="padding:10px;border:1px solid #e0e0e0;"><b>Excess</b></td>
          <td style="padding:10px;border:1px solid #e0e0e0;">+{pct - threshold:.2f}%</td>
        </tr>
      </table>
      <br>
      <p>📊 <a href="https://dune.com/amandatw/dex-wash-trading-detection-and-risk-control-framework">
        View Full Dashboard
      </a></p>
      <p style="color:#888;font-size:0.85em;">
        Auto-generated by DEX Wash Trading Monitor · {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
      </p>
    </body></html>
    """

    msg               = MIMEMultipart("alternative")
    msg["Subject"]    = subject
    msg["From"]       = SMTP_USER
    msg["To"]         = ALERT_TO
    msg.attach(MIMEText(html, "html"))
    return msg


def send_email(msg: MIMEMultipart) -> None:
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_USER, ALERT_TO, msg.as_string())
    print(f"[INFO] Alert email sent to {ALERT_TO}")


# === Main ===

def main() -> None:
    print(f"[START] {datetime.now(timezone.utc).isoformat()}")
    print(f"[INFO]  Query ID : {QUERY_ID}")
    print(f"[INFO]  Threshold: {THRESHOLD}%")

    # 1. Run Dune query
    execution_id = execute_query(QUERY_ID)

    # 2. Wait for results
    rows = wait_for_results(execution_id)
    print(f"[INFO] Rows received: {len(rows)}")

    # 3. Parse latest wash trading %
    date, pct = get_latest_wash_pct(rows)
    print(f"[RESULT] {date} → {pct:.2f}%")

    # 4. Alert if above threshold
    if pct > THRESHOLD:
        print(f"[ALERT] {pct:.2f}% > {THRESHOLD}% → sending email...")
        msg = build_email(date, pct, THRESHOLD)
        send_email(msg)
    else:
        print(f"[OK] {pct:.2f}% ≤ {THRESHOLD}% → no alert needed")

    print("[DONE]")


if __name__ == "__main__":
    main()